
CREATE TABLE public.PARTY (
                PARTY_ID BIGINT NOT NULL,
                PARTY_TYPE VARCHAR NOT NULL,
                CONSTRAINT party_id PRIMARY KEY (PARTY_ID)
);


CREATE TABLE public.ORG (
                ORG_ID BIGINT NOT NULL,
                ORG_PARTY_ID BIGINT NOT NULL,
                PARTY_NAME VARCHAR NOT NULL,
                CONSTRAINT org_id PRIMARY KEY (ORG_ID, ORG_PARTY_ID)
);


CREATE TABLE public.INDIVIDUAL (
                INDIVIDUAL_ID BIGINT NOT NULL,
                INDIVIDUAL_PARTY_ID BIGINT NOT NULL,
                GIVEN_NAME VARCHAR NOT NULL,
                MIDDLE_NAME VARCHAR,
                FAMILY_NAME VARCHAR NOT NULL,
                BIRTH_DATE DATE NOT NULL,
                CONSTRAINT individual_id PRIMARY KEY (INDIVIDUAL_ID, INDIVIDUAL_PARTY_ID)
);


CREATE TABLE public.PARTY_ROLE_ASSIGNMENT (
                PARTY_ROLE_ASSIGNMENT_ID BIGINT NOT NULL,
                ROLE_ASSIGN_PARTY_ID BIGINT NOT NULL,
                ROLE_BEGIN_DATE DATE NOT NULL,
                ROLE_END_DATE DATE,
                PARTY_ROLE_TYPE VARCHAR NOT NULL,
                CONSTRAINT party_role_assignment_id PRIMARY KEY (PARTY_ROLE_ASSIGNMENT_ID, ROLE_ASSIGN_PARTY_ID)
);


ALTER TABLE public.PARTY_ROLE_ASSIGNMENT ADD CONSTRAINT party_party_role_assignment_fk
FOREIGN KEY (ROLE_ASSIGN_PARTY_ID)
REFERENCES public.PARTY (PARTY_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.INDIVIDUAL ADD CONSTRAINT party_individual_fk
FOREIGN KEY (INDIVIDUAL_PARTY_ID)
REFERENCES public.PARTY (PARTY_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.ORG ADD CONSTRAINT party_org_fk
FOREIGN KEY (ORG_PARTY_ID)
REFERENCES public.PARTY (PARTY_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;
