
CREATE TABLE public.ITEM (
                ITEM_ID BYTEA NOT NULL,
                ITEM_DESCRIPTION VARCHAR NOT NULL,
                LIST_PRICE BIGINT NOT NULL,
                CONSTRAINT item_id PRIMARY KEY (ITEM_ID)
);


CREATE TABLE public.PHONE (
                FULL_PHONE_NUMBER BIGINT NOT NULL,
                AREA_CODE SMALLINT NOT NULL,
                PHONE_NUMBER BIGINT NOT NULL,
                EXTENSION_NUMBER INTEGER,
                DEVICE_TYPE VARCHAR NOT NULL,
                CONSTRAINT phone_id PRIMARY KEY (FULL_PHONE_NUMBER)
);


CREATE TABLE public.EMAIL (
                EMAIL_ADDRESS VARCHAR NOT NULL,
                CONSTRAINT email_address PRIMARY KEY (EMAIL_ADDRESS)
);


CREATE TABLE public.POSTAL_ADDRESS (
                POSTAL_ADDRESS_ID BYTEA NOT NULL,
                ADDRESS_LINE1 VARCHAR NOT NULL,
                ADDRESS_LINE2 VARCHAR,
                CITY VARCHAR,
                STATE_PROVINCE_CODE INTEGER NOT NULL,
                COUNTRY_CODE SMALLINT NOT NULL,
                POSTAL_CODE INTEGER NOT NULL,
                CONSTRAINT postal_address_id PRIMARY KEY (POSTAL_ADDRESS_ID)
);


CREATE TABLE public.ORG_TYPE (
                ORG_TYPE_CODE SMALLINT NOT NULL,
                ORG_TYPE_DESCRIPTION VARCHAR NOT NULL,
                CONSTRAINT org_type_code PRIMARY KEY (ORG_TYPE_CODE)
);


CREATE TABLE public.PARTY (
                PARTY_ID BYTEA NOT NULL,
                PARTY_TYPE CHAR NOT NULL,
                CONSTRAINT party_id PRIMARY KEY (PARTY_ID)
);
COMMENT ON COLUMN public.PARTY.PARTY_TYPE IS 'Types: CUS=CUSTOMER, SUP=SUPPLIER, EMP=EMPLOYEE';


CREATE TABLE public.PARTY_PHONE (
                PARTY_FULL_PHONE_NUMBER BIGINT NOT NULL,
                PHONE_PARTY_ID BYTEA NOT NULL,
                PHONE_TYPE CHAR NOT NULL,
                CONSTRAINT phone_party_id PRIMARY KEY (PARTY_FULL_PHONE_NUMBER, PHONE_PARTY_ID)
);


CREATE TABLE public.PARTY_EMAIL (
                EMAIL_PARTY_ID BYTEA NOT NULL,
                PARTY_EMAIL_ADDRESS VARCHAR NOT NULL,
                EMAIL_TYPE CHAR NOT NULL,
                CONSTRAINT email_party_id PRIMARY KEY (EMAIL_PARTY_ID, PARTY_EMAIL_ADDRESS)
);


CREATE TABLE public.PARTY_POSTAL_ADDRESS (
                PARTY_POSTAL_ADDRESS_ID BYTEA NOT NULL,
                POSTAL_PARTY_ID BYTEA NOT NULL,
                ADDRESS_TYPE CHAR NOT NULL,
                CONSTRAINT party_postal_address_id PRIMARY KEY (PARTY_POSTAL_ADDRESS_ID, POSTAL_PARTY_ID)
);


CREATE TABLE public.ORG (
                ORG_ID BYTEA NOT NULL,
                ORG_PARTY_ID BYTEA NOT NULL,
                PARTY_NAME VARCHAR NOT NULL,
                Parent_ORG_ID BYTEA NOT NULL,
                ORG_ORG_TYPE_CODE SMALLINT NOT NULL,
                CONSTRAINT org_id PRIMARY KEY (ORG_ID)
);


CREATE TABLE public.INDIVIDUAL (
                INDIVIDUAL_ID BYTEA NOT NULL,
                INDIVIDUAL_PARTY_ID BYTEA NOT NULL,
                GIVEN_NAME VARCHAR NOT NULL,
                MIDDLE_NAME VARCHAR,
                FAMILY_NAME VARCHAR NOT NULL,
                BIRTH_DATE DATE NOT NULL,
                CONSTRAINT individual_id PRIMARY KEY (INDIVIDUAL_ID)
);


CREATE TABLE public.PARTY_ROLE_ASSIGNMENT (
                PARTY_ROLE_ASSIGNMENT_ID BYTEA NOT NULL,
                ROLE_ASSIGN_PARTY_ID BYTEA NOT NULL,
                ROLE_BEGIN_DATE DATE NOT NULL,
                ROLE_END_DATE DATE,
                PARTY_ROLE_TYPE VARCHAR NOT NULL,
                CONSTRAINT party_role_assignment_id PRIMARY KEY (PARTY_ROLE_ASSIGNMENT_ID)
);


CREATE TABLE public.PURCHASE_ORDER (
                PURCHASE_ORDER_NUMBER BYTEA NOT NULL,
                ORDER_DATE DATE NOT NULL,
                ORDER_STATUS CHAR NOT NULL,
                SUPPLIER_ROLE_ASSIGNMENT_ID BYTEA NOT NULL,
                CONSTRAINT purchase_order_number PRIMARY KEY (PURCHASE_ORDER_NUMBER)
);


CREATE TABLE public.PURCHASE_ORDER_ITEM (
                PURCHASE_ITEM_ID BYTEA NOT NULL,
                ITEM_PURCHASE_ORDER_NUMBER BYTEA NOT NULL,
                ITEM_PURCHASE_UNIT_PRICE BIGINT NOT NULL,
                ITEM_PURCHASE_QUANTITY BIGINT NOT NULL,
                CONSTRAINT purchase_order_item_number PRIMARY KEY (PURCHASE_ITEM_ID, ITEM_PURCHASE_ORDER_NUMBER)
);


ALTER TABLE public.PURCHASE_ORDER_ITEM ADD CONSTRAINT item_purchase_order_item_fk
FOREIGN KEY (PURCHASE_ITEM_ID)
REFERENCES public.ITEM (ITEM_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.PARTY_PHONE ADD CONSTRAINT phone_party_phone_fk
FOREIGN KEY (PARTY_FULL_PHONE_NUMBER)
REFERENCES public.PHONE (FULL_PHONE_NUMBER)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.PARTY_EMAIL ADD CONSTRAINT email_party_email_fk
FOREIGN KEY (PARTY_EMAIL_ADDRESS)
REFERENCES public.EMAIL (EMAIL_ADDRESS)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.PARTY_POSTAL_ADDRESS ADD CONSTRAINT postal_address_party_postal_address_fk
FOREIGN KEY (PARTY_POSTAL_ADDRESS_ID)
REFERENCES public.POSTAL_ADDRESS (POSTAL_ADDRESS_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.ORG ADD CONSTRAINT org_type_org_fk
FOREIGN KEY (ORG_ORG_TYPE_CODE)
REFERENCES public.ORG_TYPE (ORG_TYPE_CODE)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.PARTY_ROLE_ASSIGNMENT ADD CONSTRAINT party_party_role_assignment_fk
FOREIGN KEY (ROLE_ASSIGN_PARTY_ID)
REFERENCES public.PARTY (PARTY_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.INDIVIDUAL ADD CONSTRAINT party_individual_fk
FOREIGN KEY (INDIVIDUAL_PARTY_ID)
REFERENCES public.PARTY (PARTY_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.ORG ADD CONSTRAINT party_org_fk
FOREIGN KEY (ORG_PARTY_ID)
REFERENCES public.PARTY (PARTY_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.PARTY_POSTAL_ADDRESS ADD CONSTRAINT party_party_postal_address_fk
FOREIGN KEY (POSTAL_PARTY_ID)
REFERENCES public.PARTY (PARTY_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.PARTY_EMAIL ADD CONSTRAINT party_party_email_fk
FOREIGN KEY (EMAIL_PARTY_ID)
REFERENCES public.PARTY (PARTY_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.PARTY_PHONE ADD CONSTRAINT party_party_phone_fk
FOREIGN KEY (PHONE_PARTY_ID)
REFERENCES public.PARTY (PARTY_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.ORG ADD CONSTRAINT org_org_fk
FOREIGN KEY (Parent_ORG_ID)
REFERENCES public.ORG (ORG_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.PURCHASE_ORDER ADD CONSTRAINT party_role_assignment_purchase_order_fk
FOREIGN KEY (SUPPLIER_ROLE_ASSIGNMENT_ID)
REFERENCES public.PARTY_ROLE_ASSIGNMENT (PARTY_ROLE_ASSIGNMENT_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.PURCHASE_ORDER_ITEM ADD CONSTRAINT purchase_order_purchase_order_item_fk
FOREIGN KEY (ITEM_PURCHASE_ORDER_NUMBER)
REFERENCES public.PURCHASE_ORDER (PURCHASE_ORDER_NUMBER)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;
